practicing functions

diff --git a/11-functions b/11-functions
--- a/11-functions
+++ b/11-functions
@@ -11,3 +11,16 @@ then
 else   
     echo "Your are a super user"
 fi
+
+
+
+sudo yum install tree -y
+
+if [ $? ne 0 ]
+then    
+    echo "tree installation is failure"
+    exit 1
+else
+    echo "tree installation is success"
+fi
+
